image: Visual Studio 2017

branches:
  only:
    - master
    - develop
    - /release\/.+/
    - /hotfix\/.+/


skip_commits:
  files:
    - '**/*.md'
    - '**/*.txt'

install:
  - cmd: git submodule -q update --init

build_script:
  - ps: .\build.ps1

artifacts:
  - path: .\bin\net35
    name: UnityFx.Mvc-net35
  - path: .\bin\net46
    name: UnityFx.Mvc-net46
  - path: .\bin\netstandard2.0
    name: UnityFx.Mvc-netstandard2.0
  - path: .\bin\*.nupkg

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '$(GitVersion_MajorMinorPatch)'
  package_version: '$(GitVersion_NuGetVersionV2)'
  assembly_version: '$(GitVersion_AssemblySemVer)'
  file_version: '$(GitVersion_MajorMinorPatch).$(GitVersion_CommitsSinceVersionSource)'
  informational_version: '$(GitVersion_InformationalVersion)'

deploy:
  - provider: GitHub
    tag: v$(GitVersion_MajorMinorPatch)
    auth_token:
      secure: aTd8m7PLWUlE3iacD7bx9oWPW/CK0+BTE7/nhgB2EXk8iZ3FJ/TJX5kKLIYP76nN
    force_update: false
    on:
      branch: master
